version: '3.7'

volumes:
  redis_data:
    driver: local

services:
  web:
    build: ./project
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./project:/usr/src/app/
    ports:
      - 1337:8000
    environment:
      - DEBUG=1
      - SECRET_KEY=dbaa1_i7%*3r9-=z-+_mz4r-!qeed@(-a_r(g@k8jo8y3r27%m
      - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
      - CELERY_BROKER=redis://:celery@redis:6379/0
      - CELERY_BACKEND=redis://:celery@redis:6379/0
      - TZ=Europe/Paris
    depends_on:
      - redis
  
  celery_beat_worker:
    build: ./project
    command: celery -A core worker -n worker1@%h -B -E -l INFO --scheduler django_celery_beat.schedulers:DatabaseScheduler --logfile=logs/celery.log
    volumes:
      - ./project:/usr/src/app
    environment:
      - DEBUG=1
      - SECRET_KEY=dbaa1_i7%*3r9-=z-+_mz4r-!qeed@(-a_r(g@k8jo8y3r27%m
      - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
      - CELERY_BROKER=redis://:celery@redis:6379/0
      - CELERY_BACKEND=redis://:celery@redis:6379/0
      - TZ=Europe/Paris
    depends_on:
      - web
      - redis

  dashboard:
    image: mher/flower:latest
    command:  date && flower --port=5555 --broker=redis://:celery@redis:6379/0
    ports:
      - 5555:5555
    environment:
      - CELERY_BACKEND=redis://redis:6379/0
      - TZ=Europe/Paris
    depends_on:
      - web
      - redis
      - celery_beat_worker

  redis:
    image: docker.io/bitnami/redis:6.2
    environment:
      - TZ=Europe/Paris
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
      - REDIS_PASSWORD=celery
    volumes:
      - 'redis_data:/bitnami/redis/data'
